---

plugins:
  # https://github.com/benmosher/eslint-plugin-import
  - import

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  jest: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  #object-curly-newline: ["error", { "minProperties": 5 }]
  #object-curly-newline: 'off'
  